### ISSUE TITLE
cwd not working as expected

### ISSUE THREAD

**Issue by tenub** [jonschlinkert/copy#9] opened 2016-05-04 04:35 UTC
Maybe I'm just confused, but with the following command I expect `build/filename.ext` to be copied to `dist/plugins/filename.ext`:

``` javascript
copy(`filename.ext`, `dist/plugins`, { cwd: 'build' }, err => {
    if (err) throw err;
});
```

Currently nothing is copied.

**Comment by jonschlinkert** [comment] 2016-05-04 04:44
this is a duplicate of https://github.com/jonschlinkert/copy/issues/8. I just updated the title, it wasn't clear that it was a duplicate before. working on a fix, thx

**Closed as completed by jonschlinkert** 2016-05-04 04:44 UTC
